### ISSUE TITLE
Firebase: Use Firebase Admin Python SDK instead of Pyrebase

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#100]
Right now we use Pyrebase (A simple python wrapper for the Firebase API) for communication between Firebase Realtime Database and Pyhton-Mapswipe-Workers. Pyrebase was not updated for over two years now. There is a official [Firebase Admin Python SDK](https://firebase.google.com/docs/admin/setup?authuser=0#add_firebase_to_your_app) available via pip. It works very similar to Pyrebase.

```python
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

# Fetch the service account key JSON file contents
cred = credentials.Certificate('path/to/serviceAccountKey.json')

# Initialize the app with a service account, granting admin privileges
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://databaseName.firebaseio.com'
})

# As an admin, the app has access to read and write all data, regradless of Security Rules
ref = db.reference('restricted_access/secret_document')
print(ref.get())
```
Set, update, push and transaction are available for save data.
For mor information: https://firebase.google.com/docs/database/admin/start?authuser=0

**Comment by Hagellach37** [comment]
hey @Matthias-Schaub ,
could you have a look at this part again and load the database url from the config.

https://github.com/mapswipe/python-mapswipe-workers/blob/c90f2621c14f2d286399de37051162fabef97ade/mapswipe_workers/basic/auth.py#L40

**Comment by Matthias-Schaub** [comment]
The official firebase python sdk is no in use.
auth.firebaseDB()
```python
    # Fetch the service account key JSON file contents
    cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
    config = load_config()
    databaseURL = config['firebase']['database_url']

    # Initialize the app with a service account, granting admin privileges
    firebase_admin.initialize_app(cred, {
        'databaseURL': databaseURL
    })

    return db
```

Use example:
```python
fb_db = auth.firebaseDB()
ref = fb_db.reference(f'projects/{project_id}/')
project = ref.get()
```
