### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#109]
Setup Travis CI to make sure deployment works after changes to code base where made:
https://travis-ci.org/

**Comment by Hagellach37** [comment]
there is an initial travis setup with mypy and pycodestyle now:
https://github.com/mapswipe/python-mapswipe-workers/tree/travis_setup

**Comment by Matthias-Schaub** [comment]
#269

**Comment by Matthias-Schaub** [comment]
Pull Request #298 makes it easier to run mapswipe workers without docker.
Unittest are in progress #131.

We are now at a point were we should setup Travis to run flake8 and soon also unittest. We should do so even given that flake8 and tests will fail.

To setup up Travis we need to deploy secrets to get access to Firebase.

**Comment by Matthias-Schaub** [comment]
TODO:

- [ ] run flake8, black and mypy
- [ ] install mapswipe_workers using pip
- [ ] setup Docker Postgres.
- [ ] create secrete for serviceAccountKey
- [ ] run unittest

**Comment by Matthias-Schaub** [comment]
Adressed in #308
