### ISSUE TITLE
Add new project attributes

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#112]
Add new project attributes:
- country
- centroid
- mappedAreaImage
- purposeMessage/thankYouMessage
- exampleImage
- exampleMessage
- scale? -> (User feedback: what is the actual size of a square on MapSwipe? I was trying to find it myself but with no success...)

exampleImage and exampleMessage are to give show the user what to map for. Those could be displayed either at the start of mapping a group and/or when clicking the information button (top right of the screen).
This idea is based on feedback from the community: "Looking for buildings in Chad is fun...but it would be good to have a frame of reference (i.e. one of two slides showing what houses in Chad might look like!)"

purposeMessage/thankYouMessage should describe the porpuse of a project very briefly (>140 chars) and will be shown to the user from time to time when finishing a group.

**Comment by jhenshall** [comment]
This would be awesome! Especially the example image and message.

Can we also add the following as parameters:
- Requesting organisation
- Task number (for projects that have to split up)
- Location (maybe. I like having country, but might want to be more specific, e.g. region?)

**Comment by Hagellach37** [comment]
closing because we don't have any urgent need and use case for this now.
