### ISSUE TITLE
Postgres: Implement general statistics as a single view (named query)

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#120]
Make sure Mapswipe Workers will access this view only when things have changed.

**Comment by Hagellach37** [comment]
also need to work on the python side of things

**Comment by Hagellach37** [comment]
almost done, just need to make sure that we update only projects that actually need an update.

Default will be: update all projects and users

But in our workflow, project_ids and user_ids from transfer_results will be used to generate stats only for things that changed.

We need to make sure that `transfer_results` returns a list of project_ids and user_ids and then need to implement that logic into `mapswipe_workers.py`

**Comment by Hagellach37** [comment]
current solution gets all project_ids and user_ids from the `result_temp` table. These are considered to need an update.

However, default option is still to update all
