### ISSUE TITLE
Rewrite transfer_to_postgres module to be transactional

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#121]
Right now the user data gets updated first then the results will be transfered (transfer_results is transactional). 

Desired workflow is:
1. Get all results from fb
2. Get all new useres from fb
3. Save new users to pg
4. Save new results to pg
5. Delete results from fb

- project.status needs to be updated as well. How to do this without asking for all projects including all metadata?

**Comment by Hagellach37** [comment]
@Matthias-Schaub I think we have this already, right? Or is there something additional?
