### ISSUE TITLE
progress as csv

### ISSUE THREAD

**Issue by maze2point0** [mapswipe/python-mapswipe-workers#126]
I came across a request to get the progress and contributor evolution in a specific time period. Right now the api/progress data is in json. Non-technical users can not easy get the information they need. Further the json structure does not support automatic conversion tools. Right now the strucutre is three keys "timestamp", "progress", "contributors". In order that a generic conversion tool can handle the structure it should be like this: 
```
{{
 "timestamp": X,
"progress": X,
"contributors": X},
{
"timestamp" YY
...}}
```

**Comment by Matthias-Schaub** [comment]
#120
