### ISSUE TITLE
Firebase Functions: get_new_group()

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#134]
Currently groups are selected by the app using order by required_count query. 
This leads first to returning the same group to a lot of users, when they requesting in the same time period (as long as nobody finished the group). Secondly it is not excluded that a user gets the same group twice.

Solutions could be:
- A flag in the database that signals if a group is currently mapped
- A Firebase Fuctions with sophisticated selection algorithm

**Comment by Hagellach37** [comment]
this has been addressed on the app side
