### ISSUE TITLE
Project Drafts: submissionKey and createdBy

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#135]
With the updated project manager dashboard only users with specific roles can create projects. The `submisssionKey` is therefore not needed anymore. At the same time we store the id of the user who created the project as `createdBy`.

- [ ] remove submission key attribute check from mapswipe_workers

**Comment by Matthias-Schaub** [comment]
Removed submissionKey check in mapswipe workers.
Added createdBy into the firebase data structure diagram.
