### ISSUE TITLE
Firebase: Migrate user stats/level/badges to v2

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#137]
Currently we have the following information:
```
{
"contributions":371,
"distance":30,
"username":"mapswiper"
}
```

The new profile will look like this:
```
{
  "contributions" : {
    "-LmAOi1QGbikKudAuf4Q" : {
      "156" : {
        "endTime" : "2019-06-18T16:14:04.405Z",
        "startTime" : "2019-06-18T16:09:04.405Z",
        "timestamp" : "2019-06-18T16:14:04.405Z"
      }
    },
    "-LmAOi5Fv6FJbro0M8OK" : {
      "101" : {
        "endTime" : "2019-06-18T16:14:04.405Z",
        "startTime" : "2019-06-18T16:09:04.405Z",
        "timestamp" : "2019-06-18T16:14:04.405Z"
      }
    }
  },
  "created" : "2019-08-13T16:34:40.948817",
  "groupContributionCount" : 2,
  "projectContributionCount" : 2,
  "taskContributionCount" : 342,
  "timeSpentMapping" : 360,
  "username" : "mapswiper"
}
```

Once a users updates the old app to the new version the app should create a new user at ref `v1/users/{old_id}` with the old user id as key. `username` should stay the same. `created` should be NULL and the other values should be set to 0. At some point we will infer from the old user statistics (`contributionCount` and `distance`) and in the past generated results the new statistics and write them back to Firebase.  

To generated to those "new" stats the following approach would be possible:
* query all user contributions from the postgres database 
* get the number of projects and number of groups --> `projectContributionCount`, `groupContributionCount`
* once we have all groups we could compute the `taskContributionCount`

There is not straigh forward way to get `timeSpentMapping` for old contributions.

**Comment by Hagellach37** [comment]
I will close this now, since we will have a bigger discussion on the user profile and what should be provided for it
