### ISSUE TITLE
MapSwipe Workers: Configuration options not needed?

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#138]
Do we need all those value key pairs for successful running of mapswipe workers?
As far as I can tell only the database_url is needed by the auth.py module:   

```json
 "firebase": {
        "api_key": "your_firebase_api_key",
        "auth_domain": "your_firebase_auth_domain",
        "database_url": "your_firebase_database_url",
        "storage_bucket": "your_firebase_storage_bucket",
        "service_account": "serviceAccountKey.json"
    },
```

```python
def firebaseDB():
    try:
        # Is an App instance already initialized?
        # Then return the Firebase Realtime Database module
        firebase_admin.get_app()
        return db
    except ValueError:
        # Fetch the service account key JSON file contents
        cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
        config = load_config()
        databaseURL = config['firebase']['database_url']

        # Initialize the app with a service account, granting admin privileges
        firebase_admin.initialize_app(cred, {
            'databaseURL': databaseURL
        })

        # Return the Firebase Realtime Database module
        return db

```

**Comment by Hagellach37** [comment]
actually ist not the database url, but the **project-name** that we need. The database url and all the other attributes will be composed out of this.

```
cred = credentials.Cert('path/to/serviceKey.json')
firebase_admin.initialize_app(cred, {
    'databaseURL' : 'https://PROJECT-NAME.firebaseio.com'
})
```

**Comment by mathcass** [comment]
For my response, I'm assuming that this is referring to the `dev` version of the app in its current state. 

Based on a read of [Firebase Admin setup docs](https://firebase.google.com/docs/admin/setup/#initialize_the_sdk), I don't even think you need the `databaseURL` as that is likely embedded in the application credentials here. 

I actually get the impression that 

```
cred = credentials.Cert('path/to/serviceKey.json')
firebase_admin.initialize_app(cred)
```

is likely sufficient for setting this up.

**Comment by Matthias-Schaub** [comment]
Hey @mathcass,
yes you are right. This is referring to the dev version of the app. Now we are using the official Firebase Admin package.
It is possible to initialize the app without the database url. But when working with the database module (Admin Database API of Firebase) it looks like the database url is needed:

```python
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
firebase_admin.initialize_app(cred)

ref = db.reference('v2/projectDrafts/')

# Will throw a ValueError: Invalid database URL: "None". Database URL must be a non-empty URL string.
```

**Comment by Matthias-Schaub** [comment]
Now the database URL is generated using the database name definined in config/config.json and used to initialize the app. Other Firebase related key-value pairs in the config are removed.

Please feel free to reopen the issue if there is more elegant solution :)
