### ISSUE TITLE
Firebase Tools: docker container firebase_deploy does have insufficient authentication scopes

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#139]
Authetication of the firebase tools inside the docker container should be done using Firebase_Token. Currently the token gets passed to the container using environment vars.

Following error occures:

Error: HTTP Error: 403, Request had insufficient authentication scopes.

**Comment by Hagellach37** [comment]
fixed in 98d8a9dbaa64c5c71e6b1a5aaadca45dfdb75dc6
