### ISSUE TITLE
Slack / Sentry utilization

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#141]
Right now only succesfull project creations will be posted in slack.
Which informations should be posted to the mapswipe backend slack channel?

### Sentry
* [x] get all Errors raised by python
* [x] don't init sentry when running tests 
* [x] update example config and doc with information about sentry

### Slack
* [x] send slack message when projects have been created successfully
* [x] send a slack message when project creation failed due to caught error
* [x] send slack message for every exception during mapswipe_workers command line tool
* [x] update example config and doc with information about slack

**Comment by laurentS** [comment]
I would also setup sentry for uncaught errors, it's been a lifesaver for me on other projects https://docs.sentry.io/error-reporting/quickstart/?platform=python

**Comment by laurentS** [comment]
Here's a link about using sentry for google cloud functions https://github.com/getsentry/sentry-javascript/issues/2122

**Comment by laurentS** [comment]
I've created a project for the python workers at https://sentry.io/missingmaps/python-mapswipe-workers/getting-started/python/ (just ask me for credentials over slack to get access)

**Comment by Hagellach37** [comment]
make sure to update config and doc,
we now need also a sentry config.
