### ISSUE TITLE
transfer results script is too slow for many results

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#15]
When many results are uploaded to the mapswipe database, we may not be able to import them quick enough.

Potential bottlenecks are:
* insert into mysql database and check for duplicates
* remove entries in firebase

**Comment by mathcass** [comment]
For clarity here, does 'mapswipe database' here refer to Firebase or the MySQL database or even something at Heidelberg? 

Is there a number (or even a guess at order like 10s, 100s, 1000s, 10000s+) of what too many results looks like here?

**Comment by Hagellach37** [comment]
Hey,
'mapswipe database' refered to the firebase database. That's the database into which user upload there contributions. More than 1000 results per minute was definitely too much, we even struggleg with 200 results per minute that came in constantly over a hour or so. 
But with the new approach, this is not a problem anymore. Now we can handle 10000+ results per minute easily.
