### ISSUE TITLE
Only useful messages in Slack

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#199]
Only send mesages useful for project managers in slack. All the other messages, and error logs should be going to sentry or into the logs only.

In slack we want:
* [x] successfull project creation
* [x] failed project creation
* [x] ~project progress reached 90%~
* [x] ~project progress reached 100%~

Also regarding the slack token:
* [x] make sure to not use the "benni" slack token

**Comment by Matthias-Schaub** [comment]
To keep things simply Sentry and Logs should contain the same information.
Sentry (sentry_sdk.init()) should already recive all logging events with level error including previous logs at info level or high as "breadcrumbs" attached to it.
I propose to take another look into this to make sure logs from the logging module are also send to sentry. This way there is no need to consult to logging systems in case one must do so.

Another proposal would be to send Slack messages only from the cli module (mapswipe_workers.py). From there after success or failure of a major routine of the program (like add a new project) information can be sent to project administrators and others in Slack. This would make the program more consise.
