### ISSUE TITLE
Minor amendments to project manager frontend

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/python-mapswipe-workers#206]
In advance of more significant changes to the front end with different parameters, can we make some minor changes to ease adding projects and reduce the need to access firebase.

* [x] Change the default group size to 120
* [x]  Increase the character limit of the Name field. Also add an example above for the format:
[project topic] - [country] (task number) \n[requesting organisation]
e.g. Disaster preparedness - Indonesia (1) \nBritish Red Cross
* [x] Can we auto fill the imagery credits depending on what tile server is selected?

**Comment by Hagellach37** [comment]
it's not really autofill of imagery credits, but good enough for now... ;)
