### ISSUE TITLE
Use a config.json similar to the one used in mapswipe

### ISSUE THREAD

**Issue by ericboucher** [mapswipe/python-mapswipe-workers#23]
Ideally, we should be able to use the exact same file in the frontend and the backend

**Comment by Matthias-Schaub** [comment]
@ericboucher Do you mean instead of your_config_file.cfg?

There should also be just one configuration file for the user to make changes. Right now the user has to make changes on multiple files to get Mapswipe running (.ENV and your_config_file.cfg).

**Comment by ericboucher** [comment]
Yes, the overall idea was to try and have a more similar setup for the backend and the frontend. I don't have a string opinion on how, but starting with a similar config file could work.

If the config file is not committed, do we still need a .env? @Matthias-Schaub

**Comment by Matthias-Schaub** [comment]
@ericboucher Can you provide a copy of the config.json for mapswipe frontend? Could not find it in the repository.

Currently the .env file is used by Docker (docker-compose).
And I think that the cfg/config.cfg is used by the mapswipe_workers python package.

**Comment by mathcass** [comment]
Hey Matthias-Schaub,

You can see an example of that config here or in the next section:
https://github.com/mapswipe/mapswipe/blob/master/CONTRIBUTING.md#autogenerate-configjson
