### ISSUE TITLE
Review postgresql triggers and constraints on resutls and results_temp

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#237]
The constraints on the postgres table `results_temp` cause the following error #225 . However, we don't need to set the primary key here, since this will be checked when inserting data into the results table.

* [x] remove pkey constraint on results_temp table

Furthermore, the postgres triggers make things slower, when importing and deleting entries in postgres.

* [x] remove count trigger on results_temp table

Let's discuss what would be the best approach for the results table. I think we need to remove the trigger here as well, since this makes the insert of results much slower, than the gain of increased speed at counting.

* [x] remove count trigger on results table. 

Relates also to #234

**Comment by Matthias-Schaub** [comment]
Removed postgres row count triggers due to performance costs and removed uneeded constraints on temporary table results_temp (constraints will be met by resutls table during late transfer from results_tenp) #239

**Comment by Matthias-Schaub** [comment]
In the production database following statements were executed to remove functions and triggers associated with tracking count of tables:
```
CREATE OR REPLACE FUNCTION drop_count_trigs()
RETURNS void AS
$$
   DECLARE
      rec   RECORD;
      q     text;
   BEGIN
      FOR rec IN SELECT relname
               FROM pg_class r JOIN pg_namespace n ON (relnamespace = n.oid)
               WHERE relkind = 'r' AND n.nspname = 'public' LOOP
         q := 'DROP TRIGGER IF EXISTS ' || rec.relname || '_count ON ' || rec.relname;
         EXECUTE q;
      END LOOP;
   RETURN;
   END;
$
LANGUAGE 'plpgsql';


select drop_count_trigs();

DROP FUNCTION add_count_trigs;
DROP FUNCTION count_trig;
DROP FUNCTION init_row_counts;
DROP FUNCTION drop_count_trigs;

DROP TABLE row_counts;
```
