### ISSUE TITLE
Investigate increased Google Cloud Platform costs

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/python-mapswipe-workers#266]
Average hosting costs have increased from ~£300 to ~£500.
Investigate why this is happening.
@mathcass created a dashboard to break down by cost but @jhenshall needs to fix the link with Big Query! There is also a more detailed breakdown in GCP billing for @jhenshall to investigate.

After investigation, can we bring down costs?

**Comment by Hagellach37** [comment]
I shut down the old back end server today (01-15-2020 ~2pm UTC). Maybe you can check if you see the effect of this in the billing logs.

**Comment by jhenshall** [comment]
Great stuff! I'll take a look when I can. And we can see what the bill is like on the first of next month.

**Comment by jhenshall** [comment]
Checked and the billing is still being exported to Big Query (nothing had been changed). But GCP now provide much better reporting. The increase is since September and in the Compute Engine product (which is the majority of our running cost). Will check again next month now change has been made.
