### ISSUE TITLE
Send Exceptions to Sentry

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#268]
When Exceptions are catched, they should be send to Sentry as well. This is not the case in the all modules/code. Sentry messages should always be send after logging calls so that those logging messages are send to Sentry as "breadcrumbs" as well (This is done by default by the sentry_sdk).

```python
except CustomError:
    logger.exception()
    sentry.capture_exception()
```

**Comment by Hagellach37** [comment]
#438
