### ISSUE TITLE
Add functionality: Delete Projects

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#294]
From time to time projects get created but never worked on. We need the option to delete these projects. This can be done similar to archiving a project.

https://github.com/mapswipe/python-mapswipe-workers/blob/82f7d68cccd0759f28fdda34e546bccf9fc606dd/mapswipe_workers/mapswipe_workers/mapswipe_workers.py#L183-L203

**Comment by Hagellach37** [comment]
Hey @Matthias-Schaub ,
sorry for being slow. but maybe we need to discuss this again. We figured out that all groups have been deleted (probably by accident) on the dev-firebase instance.

Let's double check that this can't happen whenever one uses this function with the wrong parameters. :)

**Comment by Matthias-Schaub** [comment]
Hi, no worries. 

You are right. Groups in dev-firebase where deleted during testing of delete_projects module.

Currently tests for the right parameters (not None) are done in the cli (mapswipe_workers.py). During testing only the delete_projects module was tested without the checks of the cli. Thats the reason for the accidental deletion of all groups. Sorry for that.

I will add additional checks in the delete_projects module that the produced reference is valid, meaning it will nevere delete all projects, groups, tasks or results.

**Comment by Matthias-Schaub** [comment]
Following expression will make sure that the reference to delete is at least 3 level deep, so that not all projects, groups, results or taks can be deleted:

`if not re.match("/v2/\w+/[a-zA-Z0-9|-|_]+", ref.path):`
