### ISSUE TITLE
setup docker for mapswipe workers

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#30]
@ericboucher already started to setup docker for the mapswipe workers. 

Currently we are not using docker at the backend. What's the current status and what stops us from solving this issue?

**Comment by ericboucher** [comment]
I think I was having issues with installing some of the libraries around GDAL. But we could try again.

**Comment by maze2point0** [comment]
Setup basic structure of ubuntu container with GDAL, python libraries and pm2.

**Comment by Hagellach37** [comment]
Still not clear, what will be the best approach:
many people say "one process in a container".

https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container

**Comment by Hagellach37** [comment]
There are already several docker images with python3 and gdal:

- https://github.com/thinkWhere/GDAL-Docker/blob/develop/3.6/Dockerfile

Need to setup this and install python libraries of mapswipe workers afterwards

**Comment by Hagellach37** [comment]
docker is setup for mapswipe workers.

Need to adjust the dockerfile a bit to allow parameters being passed to the dockerfile. This will be helpful to run different processes (e.g. import or update) with the correct parameters. (Ideally we can then use a single dockerfile. In docker-compose we will create 4 containers based on this dockerfile, but using different input arguments)

Need to setup docker-compose file and make sure that volumes are set correctly.

**Comment by Hagellach37** [comment]
need to make sure that logs are correctly written and errors will be handled, currently this is not clear how logs are passed from python to docker and how errors are reported or not.

**Comment by Hagellach37** [comment]
postgres, import and update are set up in docker.
need to put export and transfer results into docker-compose

**Comment by Hagellach37** [comment]
docker is set up
