### ISSUE TITLE
API: mapswipe api should use https instead of http

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#31]
currently some mapswipe data can be downloaded directly from the api:

for example:
http://api.mapswipe.org/stats.json

We should enable https for this to allow easy integration into other website, services etc.

**Comment by maze2point0** [comment]
mapswipe.org is already reachable via http and https.
However someone with access to the https://github.com/mapswipe/mapswipe.github.io may set the option _enfore https_

For api.mapswipe.org see http://nginx.org/en/docs/http/configuring_https_servers.html for documentation.
But no idea how to get a server certificate

**Comment by mathcass** [comment]
For the NGINX configuration, I'd recommend looking into Let's Encrypt for
it. There are modules to set it up automatically and have it auto renew:

https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/

**Comment by mathcass** [comment]
This post supersedes the one I put above:

https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/
