### ISSUE TITLE
Deploy with Travis CI

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#312]
This extends #109 and #308 

* [x] deploy to dev server using traving deployment (https://docs.travis-ci.com/user/deployment/script/)
* [x] put all steps needed for deployment into a script, instead of doing this partly in `before_script` section

**Comment by Matthias-Schaub** [comment]
Deployment to the Dev server is working now. Travis can now connect to the server using SSH. Ansible is used to run deployment commands on the Dev server.

**Comment by Matthias-Schaub** [comment]
See also https://mapswipe-workers.readthedocs.io/en/dev/deployment_overview.html
