### ISSUE TITLE
Simplify Tasking Manager Geometries

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#333]
Simpler geometries from MapSwipe would better integrate with HOT's Tasking Manager and could help to reduce traffic, inprove user experience, and and reduce load for Tasking Manager api.

Adjust our workflow so that we:
* use bounding box instead of convex hull
* use only 7 digits for coordinates
* provide addtional output for project extent as geojson (the extent the project manager has used to create the project in the first place)

could look like this in the end:

![Screenshot from 2020-04-28 12-56-17](https://user-images.githubusercontent.com/7045979/80480439-f213e300-8950-11ea-8815-4ed69512c013.png)

We might be even able to set up a project in the Tasking Manager with a simple aoi and arbitrary tasks utilizing the Tasking Manager api. :)

**Comment by xamanu** [comment]
Thanks, @Hagellach37 for checking on this. We just limited the standard size for file upload in the Tasking Manager to 1 MB (https://github.com/hotosm/tasking-manager/issues/2808). Please let us know if you suggest a different maximum upload size.
