### ISSUE TITLE
create documentation automatically from docstrings

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#35]
We use numpy format for the docstrings

**Comment by Hagellach37** [comment]
there is a documentation at [reathedocs](https://mapswipe-workers.readthedocs.io/en/benni.new-project-types/project_type-footprint.html)

Further things we need to improve:
* shorten and update "processes" section
* update docu for "api" using this [google doc](https://docs.google.com/document/d/1RwN4BNhgMT5Nj9EWYRBWxIZck5iaawg9i_5FdAAderw/edit#heading=h.wp1a8ue6nwhv) and afterwards update link at mapwip.org
* for "Project type structure" create screenshots for each project type and adjust data snippets
* Make sure that documentation for mapswipe-workers is complete, e.g. at the moment some modules are not documented or the documentation is not displayed (e.g. BaseFunctions)

**Comment by Hagellach37** [comment]
update the processes section

**Comment by Matthias-Schaub** [comment]
Updated the api section

**Comment by Hagellach37** [comment]
this has been solved by creating a function with loads the config in auth.py
