### ISSUE TITLE
Script for quick task generation

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#355]
Create a script which can be executed to generate taks for an input geometry (geojson).

Goal: Tasks as geojson for tutorial creation.

Need: Minimal information needed for task creation (ProjectType Class, ProjectId, ZoomLevel, TileServer, ...?)

**Comment by Hagellach37** [comment]
this has been implemented in https://github.com/mapswipe/python-mapswipe-workers/blob/master/mapswipe_workers/python_scripts/tasks_to_geojson.py
