### ISSUE TITLE
Rename build_area module to reflect usage of the module for other project types (change detection)

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#358]
With Pull request  #357 project types are now defined in definition.py. A identifier (integer) is mapped to a name (eg. BuildArea) and a class constructor for this project type. Project type BuildArea and ChangeDetection are using the same class constructor currently called BuildArea. This should be changed to reflect usage of that class for multiple project types.  

What would be a good class name?

**Comment by Hagellach37** [comment]
I would go for:

* TileMapServiceGridProject (this would apply for BuildArea and Completness and Change Detection)
* ArbitraryGeometriesProject (this would apply for Footprint)
