### ISSUE TITLE
Install GDAL >3.0 in travis

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#379]
The travis workflow currently install GDAL `2.4.2` or so, but we should install the latest GDAL version > `3.0`

we might take a look here to set up the right GDAL version:

https://github.com/mapbox/rasterio/blob/master/.travis.yml

**Comment by Matthias-Schaub** [comment]
GDAL 3.x as package is only available in ubuntu: https://packages.ubuntu.com/search?keywords=gdal
Travis uses ubuntu bionic (18.04LTS).
There is currently no way to use ubunut focal (20.04LTS) in travis.

So we either have to install the binaries manually as rasterio does.
Or maybe provide gdal through docker:
- https://github.com/OSGeo/gdal/tree/master/gdal/docker
- https://hub.docker.com/r/osgeo/gdal

**Comment by Matthias-Schaub** [comment]
Test are now run inside the docker container of mapswipe_workers, which works gdal>3.

See Pull Request #380
