### ISSUE TITLE
Changes in Results Timestamp

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#382]
The results in Firebase change slightly regarding the timestamps.

This needs to be accounted for by:
* Firebase Functions
* Firebase to Postgres in MapSwipe workers

**Comment by laurentS** [comment]
Just repeating my comment in https://github.com/mapswipe/mapswipe/pull/237 for easier tracking.

The commits in the PR don't change anything that the app sends to the backend. It only changes their names internally, and removes the `timestamp` key that is sent along with `startTime` and `endTime` in the results. So there are no new attributes. However if the backend relies on `timestamp` then you should change that to use `endTime` instead, as their values are the same.
