### ISSUE TITLE
projects for teams

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#392]
Make projects available for users which are part of a team. Users that are part of a team will see more projects in the app than "normal" users, if there are specific team projects set. Whereas it is most desirable that MapSwipe projects are open for everyone to map, some organisations have requested this option, e.g. to engage volunteers in bigger MapSwipeathons or for targeted and potentially paid mapping campaigns.

This requires several additions from the back end side:

### Firebase
* [x] adjust firebase database rules
    * users can read their team id, but can't overwrite it
    * only project managers can write team attributes in firebase
    * users can read `teamName`, but not other attributes such as `teamToken`
* [x] write tests for firebase rules 
* [x] add new data endpoint for teams at `v2/teams/teamId`
* data structure:  ```{
  "teamName": "Benni's Super Swipers",
  "teamToken": "ab234ef449ccb98e7a"
  }```

### User / Team Management
* [x] write function to set up a team using the mapswipe_workers cli team-management
    * input: team name
    * teamToken will be generated, e.g. such as a UUID using [this lib](https://github.com/uuidjs/uuid)
* [x] write a function to renew token of a team in mapswipe_workers cli team-management
* [x] write function to delete a team  in mapswipe_workers cli team-management
* [x] write function to add user to a team with given id using the mapswipe_workers cli
* [x] write function to remove all users to a give team using the mapswipe_workers cli
* [x] add basic tests:
    * create a team, then delete it. There should be nothing left
    * create a team, make sure the data is there, and the UUID has the format you expect
    * create a team, update the team token, make sure the new token is not the same as the original one

### Project Creation
* [x] adjust project creation in manager dashboard
    * add team id to project
* [x] check for teamId in projectDraft during project creation and set status accordingly
    * set status for private projects after creation to `private_inactive`

### Project Management
* [x] show all users of a team in manager dashboard
* [x] show that projects are private in manager dashboard project overview page
* [x] make sure that you can set a private project not to public by accident, valid status attributes for private projects  `private_active`, `private_finished`, `private_inactive`

**Comment by laurentS** [comment]
Here are some test ideas to validate the permission, based on the queries the app actually uses:
```python
# all the following should probably be done 4 times:
# - as a regular, non-project-manager user without teamId
# - as a project-manager user without teamId
# - as a regulat, non-project-manager user with a teamId
# - as a project-manager user with a teamId

# get a list of v2/projects/ with queryParams = ['orderByChild=status', 'equalTo=active', 'limitToFirst=20']
# get a list of v2/projects with  queryParams = ['orderByChild=teamId',`equalTo=${teamId}`,'limitToFirst=20'] this is for private projects
# fetch the user's profile under v2/users/<userid>
# get the name of the user's team at v2/teams/<teamId>/teamName
# read announcements at v2/announcement/ limitToLast=2

# get groups for a given project at v2/groups/<projectId>/<groupId>/
# get tasks for a given project/group at v2/tasks/<projectId>/<groupId>/
# write results at v2/results/<projectId>/<groupId>/

# for upcoming changes in https://github.com/mapswipe/mapswipe/issues/251
# update the user's email, password and username
```

I think this should cover it

**Comment by laurentS** [comment]
I wasn't thinking of the failing cases, but I guess you could also run all of the above as a non authenticated user, and nothing should work. And then there's all the non app stuff, but I guess you've got that covered.

**Comment by Hagellach37** [comment]
top, this sounds good
