### ISSUE TITLE
Adjust Firebase DB Rules for Team Member Registration

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#396]
There will be a registration form, which will be used by users to sign up with a team. This has several implications on Firebase's database rules.

Queries by Registration form:
* check if a `teamId` for the given `teamToken` exists
* filter teams by `teamToken` and get `teamId` and `teamName`
* set `teamId` attribute for a user that has signed up for the app through the registration form

Implications on Rules:
* [ ]  users should be able to run the query and get information on teams only if they know the `teamToken`, which will be provided by the url of the registration form.
* [ ] a user should not be able to just read all the teams and their attributes without providing a `teamToken`
* [ ] users should be able to set the `teamId` attribute in their user profile, if they provide the correct `teamToken`

* [ ] add checks for the rules above to integration tests

**Comment by Hagellach37** [comment]
@laurentS I think this should cover more or less what we discussed earlier. Anything missing?

**Comment by jhenshall** [comment]
@Hagellach37 - I think this is done so moving on the project board but tagging you in case some follow up stuff needed.
