### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#4]
While running our scripts we got this error:

```
google-mapswipe-workers: run_export.py: error occured
(<class 'requests.exceptions.HTTPError'>, HTTPError(HTTPError('401 Client Error: Unauthorized for url: https://msf-mapswipe.firebaseio.com/projects.json',), '{\n  "error" : "Unauthorized request."\n}\n'), <traceback object at 0x7fa90708b1c8>)
```

It seems is if it occurs randomly, after several minutes the error didn't occur anymore.

This seems to been a know issue with oauth2client, which us used by pyrebase: https://github.com/thisbejim/Pyrebase/issues/117

**Comment by heston** [comment]
I was looking at thisbejim/Pyrebase#117 and saw this issue was linked. PR https://github.com/thisbejim/Pyrebase/pull/249 should fix the issue in Pyrebase.
