### ISSUE TITLE
export data in json format

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#40]
Adapt this to the new structure.
We need to export:
 * users and stats
 * projects
 * project results

**Comment by maze2point0** [comment]
Adapt export to new mysql structure. Enable the option to join results with attributes of tasks.
#43

**Comment by maze2point0** [comment]
Export function for results assigns unnecessarily float datatypes to decision, yes_count, maybe_count, bad_imagery_count attributes. Error origin could be the aggregation in postgres

https://github.com/mapswipe/python-mapswipe-workers/blob/a725ad47cfd9ea65b5829face3dde9f08c41e5ff/mapswipe_workers/ProjectTypes/BuildArea/BuildAreaProject.py#L261

Or the export to json

https://github.com/mapswipe/python-mapswipe-workers/blob/a725ad47cfd9ea65b5829face3dde9f08c41e5ff/mapswipe_workers/basic/BaseProject.py#L1033
