### ISSUE TITLE
Building Footprint Project Type Data Structure

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#405]
The building footprints project type intially implemented supports polygon geometries. However, in some situations we might be able to simplify a polygon, e.g. by a bounding box or by it's centroid. This will have an effect on how much data is transferred from Firebase to the client users. (A centroid is much smaller than the entire polygon.)

However, this strongly relates to how we want to store geometry data. Storing in Firebase offers the easiest solution, but is very likely also the most expensive one. There are also other options such as [Cloud Storage](https://firebase.google.com/docs/storage), which could be used to storage all geometries of a group, which will be much cheaper.

We need to define which data is expected by the app and where it should come from.

**Comment by Hagellach37** [comment]
@laurentS just for reference here, and maybe we can think about which options we would have to store data for the tasks per group not directly in firebase, but using a cheaper service.

**Comment by Hagellach37** [comment]
I did some tests to get a sense of the data size we can expect using different ways of writing the tasks. The project contains of around 26,937 simple squares, each having 5 coordinates using 7 digits.

| # |  description | size | size/task |
| --- | ---| --- | --- |
| 1 | geometry as geojson + projectId + groupId | 8.5MB | 3.16×10⁻⁴ | 
| 2 | geometry as geojson, no projectId, no groupId | 6.7 MB | 2.49×10⁻⁴ | 
| 3 | only geometry coordinates, use `c` as the key instead of `geometry` | 5.0MB |  1.86×10⁻⁴ | 
| 4 | centroid coordinate, use `x` and `y` attributes with floats | 2.0MB | 0.74 ×10⁻⁴ |

**Comment by laurentS** [comment]
probably worth linking PR #433 that ends up using gzip + base64 encoding to shrink data size to about 750kB using the same data sample as in row 1 above.

**Comment by Hagellach37** [comment]
will be close once #436 merged into master
