### ISSUE TITLE
Deployment: pkg_resources.ContextualVersionConflict

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#425]
during deployment using docker we get the following error, which prevents the mapswipe_workers container to start.

pkg_resources.ContextualVersionConflict: (six 1.11.0 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.13.0'), {'google-api-core'})

**Comment by Matthias-Schaub** [comment]
Not quite sure what this error means. Seems like six 1.11 is installed but a newer version of it is required by another package.

When looking at the requirement file it occurred to me that we could update a few packages to their latest version (e.g. firebase-admin from 3.x to 4.x). Maybe that will also resolve above issue?

**Comment by Hagellach37** [comment]
I added six 1.15.0 to the requirements and now the deployment works. I will add a new issue to update all packages.
