### ISSUE TITLE
Firebase and postgresql based stats do not always agree

### ISSUE THREAD

**Issue by laurentS** [mapswipe/python-mapswipe-workers#449]
I'm writing this ticket mostly to keep track of a complex bug we spent hours tracking with @Hagellach37 .
In some projects, at some periods of time, there is a difference between the progress reported by the app (from firebase data) and the one reported on the mapswipe.org/data.html page (from postgresql data).
The progress shown in the app is calculated from the data in firebase, by the firebase functions, which are called each time an app uploads results for a group. The `finishedCount` attribute on a group shows how many such results have been reported by the app, and should increase by 1 every time a user completes a group. `requiredCount` is updated at the same time, but down from the initial number of users required to review each task (typically 3 or 5). These numbers are updated at the same time as the progress percentage, so are a good proxy to work out the source of the problem.
This bug is about how this `finishedCount` and `requiredCount` differ from the actual number of results seen in firebase and postgresql.
The answer seems to be that firebase functions are "guaranteed to be invoked at least once". From [the docs](https://cloud.google.com/functions/docs/concepts/exec#execution_guarantees):
> Background functions are invoked at least once. This is because of the asynchronous nature of handling events, in which there is no caller that waits for the response. The system might, in rare circumstances, invoke a background function more than once in order to ensure delivery of the event. If a background function invocation fails with an error, it will not be invoked again unless retries on failure are enabled for that function.

So we need to modify the functions so that they stop execution in case they are called more than once.
An example solution is proposed in [this stackoverflow question](https://stackoverflow.com/a/54712252/1138710).

Extra github comments from other people mentioning the issue, and google staff replies:
- https://github.com/firebase/functions-samples/issues/105
- https://github.com/firebase/firebase-functions/issues/315#issuecomment-419810580
- https://github.com/firebase/firebase-functions/issues/62#issuecomment-419810195

**Comment by Hagellach37** [comment]
Hey,
I see a few options how this could be done in firebase functions.

What we could for instance write the userId to the group object in firebase, e.g. create a structure like this:

```
groupA:
    verificationCount: 5,  // this will be set during project creation
    users:  // this will be set by a firebase function that gets triggered when a result is uploaded
      userA: true,
      userB: true,
   fininishedCount: 2,
   
```

Based on this new structure, we could re-calculate the `finsihedCount` and `requiredCount` attributes, based on the `verificationCount` and the number of userIds we get for the users attribute.

When a function would be trigerred again this would not change the counters of a group then.

**Comment by laurentS** [comment]
I'd rather avoid touching the input data as much as possible, because the app is already downloading 15 groups at the start of every group mapping session. I think we can find a way to do a shallow download, though it would complicate the code quite a bit by adding one more step in an already convoluted process. If we add all these user IDs in there, the app will download more data, and every update will also be sent to all the apps working on this group.
I think your first idea, keeping an eye on what is in the user profiles is probably easier and implies fewer data pushes to the app. When the firebase function runs, we checks whether the relevant group is already in the user's profile. If yes, we've handled it, stop there, if no, do the updates like now. If all this is in a transaction, it should be ok, no?

We could also delegate the `finishedCount` calculation to the app: right now it uses a `ref.set()` call, but I think we could manage a `ref.transaction()` instead. I'm not sure how excited I am about letting the user client update these numbers, I feel like the app should touch the absolute minimum data and let the backend do the rest.
Or we simply do what's described in that SO post: have a key in firebase where we just write the eventIDs as we handle them to avoid duplicate handling. And then we delete the old ones on a regular basis, like every X hours or something.

**Comment by Hagellach37** [comment]
I agree that we should try to change as little as possible that relates to the client side. So maybe it will be the best to check for the groupId in the user profile at the very beginning of the firebase functions workflow and if it already exists stop the entire process.

We don't want that the users can change the stats, e.g. by setting the finishedCount in the groups directly. This would have effects on the database rules and might lead to unintended behaviour, such as users randomly setting the finishedCount etc.

We can still think about adding a new path in firebase to store the userIds per group, e.g. in `v2/groupsCompleted/{project_id}/{groups_id}/users. But I need to think about it a bit further.

**Comment by Hagellach37** [comment]
it seems to be also the case that sometimes the app progress is at 99% although the progress derived from the backend is already at 100%
