### ISSUE TITLE
Change from mysql to psql

### ISSUE THREAD

**Issue by maze2point0** [mapswipe/python-mapswipe-workers#45]
As mentioned in #42 we changed our database infrastructure from mysql to psql for easier json handling.
Therefore we have to:
 * setup postgres databases (dev is already done)
 * add postgres credentials to cfg
 * go over the scripts rewrite the db connection, change the variable naming

**Comment by maze2point0** [comment]
Also we need to migrate the data currently stored in mysql to the psql database.
I propose to use a FDW for this, will test it on the dev psql with a subset of project and result data.

**Comment by maze2point0** [comment]
For the fdw we need a docker file with postgre and the mysql FDW extension. Found this:

https://github.com/GeographicaGS/Docker-Postgis-FDW/tree/master/MySQL

**Comment by Hagellach37** [comment]
Make sure to create the database in postgresql directly when setting up the database. This will make it easier for us to create the tables.

Maybe we can even think about setting up all tables directly using docker. (e.g. by running the python script in utils or using another bash command)

**Comment by Hagellach37** [comment]
hey,
when importing a project we log:
`12-04 14:42:50 WARNING  ALL - set_tasks_psql - tasks missed critical information: 'projectId'`
however, it seems that tasks will be imported. we should double check and clean up to logs and prints here.

**Comment by maze2point0** [comment]
Could not reproduce that log ```tasks missed critical information..``` which project id did you import?

**Comment by maze2point0** [comment]
Added a script for doing the migration from mysql to postgresql for project and result data.
e445b172605d6fc781b63ef5a33d71786f49f228
For the postgres docker we are using right now the following steps are needed to execute:
```apt install postgresql-9.6-mysql-fdw```

Then just run ```python3 mapswipe_workers/utils/migrate_mysql_psql.py```
If not already set up, it will activate the extension and establish a connection from pgsql to mysql.
Further materialized views, basically cached views are created for project and result(limited to 1000 for testing purposes) data. The views scheme already matches the ones we have in postgres, so for the import just an insert all statement is needed.

**Comment by maze2point0** [comment]
Tested the import via FDW:
import takes:
* Projects (162) - not even a minute
* for all results(18mio) mat view + insert ~10minutes

**Comment by Hagellach37** [comment]
Hey @maze2point0 ,
we also need a postgresl class in the auth file. Currently there is only a class for dev_postgresl.

https://github.com/mapswipe/python-mapswipe-workers/blob/2f156038a0f374d1240d0624ed2311ea03a38f4e/mapswipe_workers/basic/auth.py#L199

Just copy and paste for the moment. ;)

**Comment by maze2point0** [comment]
done in 715bd4725d79ec101438012f38e648877c3d2fcc
