### ISSUE TITLE
Simplify Firebase Functions and move project progress calculation to python backend

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#455]
This issue is a result of the discussion that we had in another issue #449, about firebase und postgres stats not showing the same values.

Basically the outcome is that Firebase functions should be idempotent.

Firebase functions should do the following things that need to happen in realtime in an idempotent way:

* [x] set `finishedCount` and `requiredCount` for a group in Firebase database
* [x] set mapping stats in the user profile (this will be used to check which groups a user already worked on)
    * [x] set `contributions` for a group in a project
    * [x] set total  `taskContributionCount` for project
    * [x]  set `taskContributionCount` for project

The python backend should do the following things, which are hard to implement in an idempotent way in Firebase:
* [x] update project `progress` in Firebase database based on results in postgres database
* [x] `contributorCount` for a project in Firebase database based on results in postgres database

**Comment by Hagellach37** [comment]
@laurentS which user stats have to be set for the app in its current state?

I think that the app only uses the `taskContributionCount` attribute. Can you confirm this?

How should we handle this in general? Should these values (and potential other user stats values) be updated by a firebase function, by the python backend or directly in the app?

**Comment by Hagellach37** [comment]
@laurentS and another question: which attribute is used to check against the maxNumberOfTasks per project in private projects?

**Comment by laurentS** [comment]
So looking through the code, I'm seeing:
- `taskContributionCount` is used in the "more" screen, to show the progress bar and level badge
- `groupContributionCount` and `projectContributionCount` are not used at this point. They are just set to `0` when a user account is created, but that's it.
- I need to document how the `maxNumberOfTasks` is used, but in short, we compare it with `v2/users/<userId>/contributions/<projectId>/taskContributionCount` (see [here](https://github.com/mapswipe/mapswipe/blob/3bb8bb762dbe00e63521815643dbb8924084fe64/src/shared/views/ProjectView.js#L454))

**Comment by laurentS** [comment]
And yes, I think these should be updated in "realtime", or at least within a minute or so, otherwise users will probably feel like something is not working.
