### ISSUE TITLE
add another process "archive" to run_mapswipe_worker

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#48]
Currently projects and all groups per project stay in firebase. Also imports stay in firebase forever. An "archive" function would help us to reduce the storage costs in firebase, increase firebase performance.

Mapswipe Workers will look at all projects in Firebase and archive them based on certain terms:
* archive flag = true (The idea is that project managers can set an archive flag to true if they decide the project is finished)

Additionally we might think about doint this automatically:
* project.progress = 100%
* No new results for e.g. 3 months

Note: Imports (projects draft) will now be deleted after successfull creation of the project

The archive function will:
* [x] set status of a project to `archived`
* [x] will delete all `tasks` and `groups` in firebase

**Comment by Hagellach37** [comment]
it should also be possible to re-activate archived projects using the data stored in the postgresql database.

**Comment by Matthias-Schaub** [comment]
Mapswipe Workers should offer a command to achive the descibed behavoir.

Mapswipe Workers will look at all projects in Firebase and archive them based on certain terms:

- project.process = 100%
- archive flag = true (The idea is that project managers can set an archive flag to true if they decide the project is finished)
- No new results for e.g. 3 months

Note: Imports (projects draft) will now be deleted after successfull creation of the project

**Comment by Hagellach37** [comment]
This has been addressed in #281 and #263
