### ISSUE TITLE
project setup for Building Footrint project type using AOI and HOT TM project id

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#492]
We would like to add new functionality to the building footprint project type, which requires changes in the project setup. The new setup should allow to create a project by providing an aoi polygon or HOT Tasking Manager project id. Based on one of these data from OSM should be downloaded and used as an input for the project creation workflow.

Things that need to be worked on:
* [x] implement function to download OSM data from ohsome api (or another API?) based on input aoi and OSM filter (e.g. just filtering for buildings)
* [x] implement a function to download HOT Tasking Manager aoi polygons from Tasking Manager API
* [x] Adjust project [setup html page](https://github.com/mapswipe/python-mapswipe-workers/blob/master/manager_dashboard/manager_dashboard/create.html) and allow users to provide one of the following:
    * direct download to geojson file
    * geojson file containing aoi multi polygon geometry
    * HOT Tasking Manager ID

For the backend workers python code check here: https://github.com/mapswipe/python-mapswipe-workers/tree/master/mapswipe_workers/mapswipe_workers/project_types/arbitrary_geometry

**Comment by ElJocho** [comment]
whats a good maximum size for the uploaded geojson in this case? Guess a geojson with multiple polygons could quickly surpass 1mb

**Comment by Hagellach37** [comment]
I think this could still be the same as we already have it. The geojson you upload via the manager dashboard should in most cases only contain one or multiple relatively simple AOI polygons. Nothing complex.

When you specify a Tasking Manager project ID it might be that you get a more complex AOI, but this is okay as it's handled by the backend.

We could think about limiting the number of features (e.g. buildings) per project. I think we don't have something like this implemented. But it might be good to check that the final number of buildings to classify is not bigger than 100k per project?

But all this will be in backend and not in the manager dashboard.
