### ISSUE TITLE
Add extra info for footprint project tasks

### ISSUE THREAD

**Issue by ElJocho** [mapswipe/python-mapswipe-workers#496]
- [x] query extra info from ohsome inluding userid, last _edited, osm_feature_id, version(how many times it got changed), source (imagery source) -> in metadata: lastedit, version, changesetid, 
- [x] this info should reach postgres via geojson but not firebase -> remove it in base/project.py/save_to_firebase
- [x] get userid and name from https://www.openstreetmap.org/api/0.6/changeset/changeset_id_we_got_from_metadata and write into properties as well -> to avoid extra queries save already queried changesetids and there response in temporary dict. ->>>> /api/0.6/changesets -> query for more changesets
- [x] adjust the way the groups are formatted, see local todo

-> clean up this issue and outline order

**Comment by Hagellach37** [comment]
could you also check if we want to add the hot tasking manager project id here as well or only at the project level.

**Comment by ElJocho** [comment]
-> input in tasks: Geojson Feature old screen, center and reference included in the geojson feature but not in property section. (take them from property section and put them out of it if its a tutorial, only tutorials have this attribute)

geojson variable -> add a comment that is only the geometry of the feature
