### ISSUE TITLE
export additional information for tasks / agg results

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#497]
For the Building Footprint project type detailed result data should be made available for download and include for each feature all metadata described in the project setup process. Each feature should additionally have the attribute of the geojson file used, e.g. osm user id, osm timestamp etc.

In postgres this information is stored in the `properties` attribute in `project_type_specifics`.

The additional attributes need to added for the following outputs:
* [x] agg_results
* [x] tasks

The additional values need to be added as new columns to the existing dataframe structure and then exported to csv/geojson.

Here we need to make sure to also load the other information available for each task:
* https://github.com/mapswipe/python-mapswipe-workers/blob/16b0254c905eb44448080c451eb5d894c9d31cd9/mapswipe_workers/mapswipe_workers/generate_stats/project_stats.py#L100

Add the attributes when merging results and tasks here
* https://github.com/mapswipe/python-mapswipe-workers/blob/16b0254c905eb44448080c451eb5d894c9d31cd9/mapswipe_workers/mapswipe_workers/generate_stats/project_stats.py#L251

**Comment by ElJocho** [comment]
#510
