### ISSUE TITLE
check if we get the changeset comments from osm api

### ISSUE THREAD

**Issue by ElJocho** [mapswipe/python-mapswipe-workers#498]

**Comment by ElJocho** [comment]
@Hagellach37 we get a comment if it is set, e.g. "RDC-Congo, Nord Kivu #hotosm-task-122, source=Bing" for https://www.openstreetmap.org/api/0.6/changeset/14372614.json

-> should we add that?

**Comment by Hagellach37** [comment]
yes, let's add it for now. But maybe let's check how "big" the geojson files get then.
