### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#52]
- [x] basic.BaseFunction.update_users_postgres()
- [x] basic.BaseFunction.run_delete()
- [x] basic.BaseFunction.run_archive()
- [x] basic.BaseFunction.run_export()
- [x] basic.BaseGroup
- [x] basic.BaseProject.set_groups_postgres()
- [x] basic.BaseProject.set_import_postgres()
- [x] basic.BaseProject.delete_tasks_postgres()
- [x] basic.BaseProject.delete_groups_postgres()
- [x] basic.BaseProject.delete_import_postgres()
- [x] basic.BaseProject.update_project()
- [x] basic.BaseProject.set_project_progress_postgres()
- [x] basic.BaseTask
- [x] ProjectTypes.BuildArea.BuildAreaGroup
- [x] ProjectTypes.BuildArea.BuildAreaProject.aggregate_results()
- [x] ProjectTypes.BuildArea.BuildAreaTask
- [x] ProjectTypes.BuildArea.GroupingFunctions
- [x] ProjectTypes.BuildArea.TileFunctions
- [x] ProjectTypes.Footprint.FootprintGroup
- [x] ProjectTypes.Footprint.FootprintProject.aggregate_results()
- [x] ProjectTypes.Footprint.FootprintTask
- [x] ProjectTypes.FootprintGroupingFunctions
- [x] utils.errorhandling
- [x] utils.slack
- [ ] utils.migrate_mysql_psql 
- [ ] basic.auth.firebase_admin_auth()
- [ ] basic.auth.dev_firebase_admin_auth()
- [ ] basic.get_api_key()
- [ ] basic.get_tileserver_url()
- [ ] basic.get_submission_key()
- [ ] basic.mysqlDB
- [ ] basic.dev_mysqlDB
- [ ] basic.psqlDB
- [ ] basic.dev_psqlDB
- [x] basic.BaseFunctions.init_import()
- [x] basic.BaseFunctions.init_project()
- [x] basic.BaseFunctions.project_exists()
- [x] basic.BaseFunctions.project_exists_firebase()
- [x] basic.BaseFunctions.project_exists_postgres()
- [x] basic.BaseFunctions.run_transfer_results()
- [x] basic.BaseFunctions.delete_project_firebase()
- [x] basic.BaseFunctions.delete_project_postgres()
- [x] basic.BaseFunctions.delete_local_files()
- [x] basic.BaseFunctions.BaseImport.BaseImport
- [x] basic.BaseFunctions.BaseImport.set_import_postgres()
- [x] basic.BaseFunctions.BaseImport.set_project_postgres()
- [x] basic.BaseFunctions.BaseImport.set_groups_postgres()
- [x] basic.BaseFunctions.BaseImport.set_tasks_postgres()
- [x] basic.BaseFunctions.BaseImport.set_project_firebase()
- [x] basic.BaseFunctions.BaseImport.set_groups_firebase()

**Comment by Hagellach37** [comment]
I will cover the grouping functions 

@maze2point0 will you go through migrate_mysql_psql when you're working on it anyway?
