### ISSUE TITLE
delete projects

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#53]
use a single sql statement to delete information in postgres instead of several functions

come up with a mechanism to delete project data in firebase and being able to roll back.

**Comment by Hagellach37** [comment]
data is deleted in firebase and postgres

not sure how to be able to roll back in firebase

**Comment by Matthias-Schaub** [comment]
Is this still up-to-date?

is "come up with a mechanism to delete project data in firebase and being able to roll back" adressed in #78 ?

`BaseFunction.delete_project_postgres()` is using mutliple sql queries, but their are sent to postgres all at once:
```python
    p_con = postgres()
    sql_insert = """
        DELETE FROM projects WHERE project_id = %s;
        DELETE FROM results WHERE project_id = %s;
        DELETE FROM tasks WHERE project_id = %s;
        DELETE FROM groups WHERE project_id = %s;
        DELETE FROM imports WHERE import_id = %s;
    """

    data = [int(project_id), int(project_id), int(project_id), int(project_id), str(import_key)]
    p_con.query(sql_insert, data)
```

**Comment by Matthias-Schaub** [comment]
Proposed solution

```    p_con = postgres()
    sql_insert = """
        BEGINN
        DELETE FROM projects WHERE project_id = %s;
        DELETE FROM results WHERE project_id = %s;
        DELETE FROM tasks WHERE project_id = %s;
        DELETE FROM groups WHERE project_id = %s;
        DELETE FROM imports WHERE import_id = %s;
        END
    """

    data = [int(project_id), int(project_id), int(project_id), int(project_id), str(import_key)]
    p_con.query(sql_insert, data)
```

**Comment by Hagellach37** [comment]
looks good

**Comment by Matthias-Schaub** [comment]
Pyrebase object: `fb_db.update(data)` acts as a transaction. If one key of data-dict is invalid the whole update will fail.

`BaseFunction.delete_project_firebase()` and `BaseFunction.delete_project_postgres()` are now both a transaction.
