### ISSUE TITLE
create index.html for nginx

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#54]
we should create an index.html file for the nginx server
this html file will provide a link to the documentation of the mapswipe api at read the docs

and furthermore show all available data sets in the respective folders.

currently there is an api documenation for the mapswipe api in a [google doc](https://docs.google.com/document/d/1RwN4BNhgMT5Nj9EWYRBWxIZck5iaawg9i_5FdAAderw/edit#heading=h.wp1a8ue6nwhv). This should be replaced with the documenation within this github repository

**Comment by Matthias-Schaub** [comment]
@ #60
