### ISSUE TITLE
Import process - Save input geometries of projects

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#55]
We create a kml or geojson during the import. This file contains the geometries for each project. The file should be stored in data/input_geometries folder and should use a better naming of the files.

e.g. `data/input_geometries/input_geometries_{id}.kml` or `data/input_geometries/input_geometries_{id}.geojson`

**Comment by Matthias-Schaub** [comment]
Ideally input geoemtries would be saved to the postgres instance.
