### ISSUE TITLE
Testing - create script which simulates setup of a project

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#57]
- [x] we need to make sure to have an user
- [x] the script should take an import and insert it to firebase
- [x] the trigger the run_import function to import the project in firebase, create groups etc and do the stuff in postgres
- [x] simulate results for the imported project
- [x] get projects
- [x] get group per project
- [x] randomly generate results for tasks
- [x] run transfer results
- [x] run update
- [x] run export

**Comment by Matthias-Schaub** [comment]
- [ ] Make sure every test data, which is generated in firebase, postgres and locally by the test scripts is deleted

**Comment by Matthias-Schaub** [comment]
See documentation for how to run tests:
https://mapswipe-workers.readthedocs.io/en/benni.new-project-types/testing.html

**Comment by Hagellach37** [comment]
we are going to run the tests in the dev environment. We need to adjust this in the setup. (make sure modus="development")

**Comment by Hagellach37** [comment]
mock results is not working for me in a docker container:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/Pyrebase-3.0.27-py3.6.egg/pyrebase/pyrebase.py", line 264, in get
    raise_detailed_error(request_object)
  File "/usr/local/lib/python3.6/site-packages/Pyrebase-3.0.27-py3.6.egg/pyrebase/pyrebase.py", line 448, in raise_detailed_error
    raise HTTPError(e, request_object.text)
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://dev-mapswipe.firebaseio.com/groups/13528/groups/13528.json?orderBy=%2522completedCount%2522&limitToFirst=5] {
  "error" : "orderBy must be a valid JSON encoded path"
}
```

**Comment by Hagellach37** [comment]
https://stackoverflow.com/questions/31867193/webbrowser-converts-double-quotes-to-2522

**Comment by Matthias-Schaub** [comment]
There is a new GitHub issue of Pyrebase describing this behaivor as well:
https://github.com/thisbejim/Pyrebase/issues/294

They are referencing to a temporarly fix of the original Firebase Database REST API:
https://firebase.google.com/docs/reference/rest/database/

In this documentation are writting:
"Query parameters in URLs require additional header: Query parameters in URLs aren't parsed correctly 
[...]
This workaround is temporary. An update expected in February 2019 will resolve issues with parsing URLs in query parameters."

**Comment by Hagellach37** [comment]
- [ ] make sure that test export does not overwrite other existing datasets, e.g. `users.json` or `stats.json`. Ideally tests would use a different `DATA_PATH`.
