### ISSUE TITLE
Server transition (Python-Mapswipe-Workers 1.5)

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#61]
- [x] Setup a **new server** (Google Compute Engine)
    - [x] Configure server backup
    - [x] Install Python-MapSwipe-Workers (do NOT run the containers)
- [x] **data transition** to new server
    - [x] Import Firebase data into Postgres (#66)
    - [x] `import`, `projects`, `groups`
   -  [x] compare amount of rows for each table firebase vs. psql
    - [x] Stop import process on the old server
- [x] Start **import process** on the new server
    - [x] update web import formular
    - [x] generate a test import in prodcution instance
    - [x] test import was successfully created in production instance
- [x] Start **transfer results** on the new server
    - [x] Migrate MySQL data (`results`) to Postgres (#65)
    - [x] test transfer results with results generated from the production app 
    - [x] stop transfer results on the old server
    - [x] transfer all results from mysql to postgresql which have not been transfered yet
    - [x] start transfer results process on the new server
- [x] Start **update** on the new server
    - [x] test update for a few old projects
    - [x] update completed count of groups in postgres
    - [x] update all projects in firebase using the new workers
    - [x] stop update on the old server
    - [x] start update process for active projects
- [x] Start **export** process on the new server
    - [x] test export for a few old projects
    - [x] manually generate exports for all projects
    - [x] stop export on the old server
    - [x] start export process for all active projects
    - [x] make sure http://api.mapswipe.org/ points to the correct ip-address
- [x] Redirect API domain name to new server
 - [x] **Shutdown old server**
    - [x] create a snapshot to backup data in *mapswipe-workers* compute engine
    - [x]  create a snapshot to backup data in cloud sql *mapswipe-db-3*
           - created dump at https://console.cloud.google.com/storage/browser/mapswipe-db-dump?project=msf-mapswipe
    - [x] wait for 2 weeks and monitor new server and processes
    - [ ] shut down compute engine *mapswipe-workers*
    - [x] shut down cloud sql *mapswipe-db-3*

**Comment by Hagellach37** [comment]
regarding 1.

I wold go for something like this: 2-CPU, 7,5GB RAM, 375GB SSD, 150GB snapshot storage --> ~65 pouns (50% of what we pay at the moment)

![grafik](https://user-images.githubusercontent.com/7045979/51613609-1ac65500-1f24-11e9-83c5-61bef279a3b4.png)
