### ISSUE TITLE
Backup routine of new production server

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#62]
What is the Backup routine of the new server?

**Comment by maze2point0** [comment]
Wee need a backup schedule! Our strategy is to create snapshots of the whole instance on a regular period (3 days - weekly; depending on the costs and time consumption)

I did a snapshot for dev instance yesterday. Size is approx. 3gb and it took less than 5minutes.
- [ ] - get more info on what the cost is
- [ ] - how to automatize it?) 
https://geekflare.com/google-cloud-vm-backup/

**Comment by Hagellach37** [comment]
the prize for the snapshots should be really low... snapshot storage is super cheap.
150GB aorund 3 pounds / month

maybe some additional network costs...

**Comment by maze2point0** [comment]
I set up a snapshot schedule: daily , snapshots older than 14 days will get deleted.

Will monitor it for the next couple of days in order to get an overview of the cost it causes

**Comment by Hagellach37** [comment]
I think creating a snapshop schedule is not enough. We need to use this schedule somehow...

**Comment by Hagellach37** [comment]
still not looking like snapshots get created

**Comment by maze2point0** [comment]
now it works. size: 14.28 GB.

Will monitor the process and costs

**Comment by maze2point0** [comment]
As far as I understood the snapshot schedule function in google cloud it works as in an incremental backup mode. The schedule is set that every day a backup is. Backups older than 14 days will be deleted. So every 14 days a full backup is done, while every day just recent changes are incrementally saved. Right now that results in around 14.3 GB full backup size and 70-80 mb increments per day.
