### ISSUE TITLE
number of active groups in last 30 days is wrong

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/python-mapswipe-workers#624]
"active groups in the last 30 days" appears to be showing the # of active contributors instead. it should be 0 in this screenshot.
<img width="744" alt="Screen Shot 2022-12-16 at 2 52 05 PM" src="https://user-images.githubusercontent.com/4806884/208178294-84cbb73d-a001-45c9-9442-fbbbbc6a3e9a.png">

**Comment by udaynwa** [comment]
We're looking into it, @danbjoseph

**Comment by thenav56** [comment]
This is fixed. Tested on https://dev-community.mapswipe.org/.


![2023-01-06-204909](https://user-images.githubusercontent.com/7059255/211038919-049861a6-d73a-4270-9154-347e783fef74.png)
