### ISSUE TITLE
thousands separator missing from chart tooltip value

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/python-mapswipe-workers#625]
<img width="527" alt="Screen Shot 2022-12-17 at 8 30 23 AM" src="https://user-images.githubusercontent.com/4806884/208244405-71ce51d7-f6e7-4364-839d-5219d4f28ad6.png">

**Comment by udaynwa** [comment]
We'll add the thousands separator.

**Comment by thenav56** [comment]
This is fixed.

![2023-01-06-205531](https://user-images.githubusercontent.com/7059255/211040051-f5470c64-c7d5-4c3d-9db3-c95361bc6e36.png)
![2023-01-06-205523](https://user-images.githubusercontent.com/7059255/211040060-68871139-4c49-4ff4-859f-9ce5807f460d.png)
