### ISSUE TITLE
Compatibility of Import formular and MapSwipe Workers

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#64]
Test compatibility of http://mapswipe.org/import with the new MapSwipe Workers.

**Comment by Hagellach37** [comment]
make sure that zoom level is passed as integer,
when using the html import formular zoom level (and potentially all other variables) are saved as string

**Comment by Hagellach37** [comment]
web import works.
need to make sure that project managers can only create "Build Area" projects production for now.

**Comment by Hagellach37** [comment]
make sure that "Submission Key" is checked and an error is raised if no/wrong key is provided.

**Comment by Hagellach37** [comment]
ae83e0317ca26b3d3f2bfc0d5c2346a9c096270a adds check for submission key

new web import formular produces an entry in firebase which is valid.
