### ISSUE TITLE
Transfer the data from MySQL to Postgres

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#65]
Write a script which transfers the data of the MySQL database to the new Postgres database.

**Comment by maze2point0** [comment]
Script is already written and workin
python-mapswipe-workers/mapswipe_workers/utils/migrate_mysql_psql.py

But no need to import projects, as in mysql just a couple of attributes, not all are stored.

**Comment by maze2point0** [comment]
wrote script under utils for importing imports and projects.
Faced a challenge with our datamodel for tasks. 
https://github.com/mapswipe/python-mapswipe-workers/commit/6c5499434c2fc9d89e646a43c7cfa63cd135066c

Some tasks dont have a project id:
https://console.firebase.google.com/project/dev-mapswipe/database/dev-mapswipe/data/groups/13541/124/tasks/13541_124_1223

For that task, the id is a combination of the project id, group id and a consecutive number. Thats fine, but inconsistent with other tasks we have in firebase. Normally we store task id and project i for each task.

**Comment by maze2point0** [comment]
for the postgresql container, it must install the mysql fdw extension in order to be able to results from mysql db when setup:
`sudo apt install postgresql-9.6-mysql-fdw`

**Comment by Hagellach37** [comment]
This means, that we need to do that in the dockerfile?

**Comment by Hagellach37** [comment]
@maze2point0 I think has already been accomplished. Correct?

**Comment by maze2point0** [comment]
Took care of the falsely taken verification count. Now all groups show the same value as their corresponding entry in the project table

**Comment by maze2point0** [comment]
> @maze2point0 I think has already been accomplished. Correct?

will create a report script which checks and logs differences in postgres and firebase. Will close here when finished.

**Comment by maze2point0** [comment]
Added a script for getting last timestamp of imported results in postgres. That one is used to get all newer results from mysql and insert them.
c2f483e504b853eed958decb9f8dcbe0c6115726
