### ISSUE TITLE
tutorial creation not using images correctly

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/python-mapswipe-workers#659]
**although 2 different images are uploaded**

<img width="1134" alt="Screen Shot 2023-03-01 at 9 04 09 AM" src="https://user-images.githubusercontent.com/4806884/222165748-e3635869-3829-4c04-acfa-fdac6b1739f7.png">

**the tutorial intro screen shows the same image twice**

<img width="500" alt="Screen Shot 2023-03-01 at 9 04 09 AM" src="https://user-images.githubusercontent.com/4806884/222166126-76763a1a-6023-41d0-b883-e604b1431197.png">

**Comment by frozenhelium** [comment]
@danbjoseph We'll look into it!

**Comment by danbjoseph** [comment]
is this fixed and can be closed?

**Comment by tnagorra** [comment]
Yes.
