### ISSUE TITLE
Documentation: How to add a new project?

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#67]
Improve documentation on how to add new projects. 
Document alongside the test scenario described in #57

**Comment by Hagellach37** [comment]
regarding this, there is google doc for project managers:
https://docs.google.com/document/d/1BGa_UfjfjVLvXWARW0mUYOFLav8F6xxcxOHaSemw5HI/edit

maybe this will be helpful or can even be merged somehow.
