### ISSUE TITLE
very similar usernames allowed and probably shouldnt be

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/python-mapswipe-workers#678]
confusing to have both a "Roxy" and a "roxy"
what controls on username duplication do we have, if any? and can we increase the restrictions?
Roxy - https://community.mapswipe.org/user/4y91DK3nbnfs75lCrINEGnBmA2m1/
roxy - https://community.mapswipe.org/user/zl5dUAGuz8aXI8oE6d4mqZWZAZa2/

**Comment by kopitek8** [comment]
Similar issue in project name as well: https://mapswipe.slack.com/archives/G721H0YRE/p1713343363909379

**Comment by kopitek8** [comment]
The update for this issue is the same as https://github.com/mapswipe/python-mapswipe-workers/issues/929#issuecomment-2162743835

**Comment by kopitek8** [comment]
UPDATE:

- For validation, user entered usernames are all saved in lower case with removed spaces. For example, the user entered username "Map Swipe 892" will be saved as "mapswipe892".
