### ISSUE TITLE
Seperation of development and production configuration necessary?

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#68]
Development and production instance of MapsSwipe Workers should not run in the same container. Therefor there is no need for a shared configuration file (no need for the fields `"dev_psql"` and `"dev_firebase"`) and also not for the `dev_firebase_admin_auth()` function and the `dev_psqlDB` class in the `auth` module.

**Comment by Matthias-Schaub** [comment]
Current code base does not support seperation. 
@Hagellach37 can I close this issue? Or should there be some kind of flag wether mapswipe workers is running in production or development mode?

**Comment by Hagellach37** [comment]
Yes, let's close the issue. In the future you will need to specify the correct firebase instance etc. directly in the configuration.
