### ISSUE TITLE
add output_path parameter to all functions which produce files

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/python-mapswipe-workers#72]
Files are produced during the **import** of new projects, when running **transfer_results** and when running the **export** process. The **delete** process uses the file path to find all files which should be deleted.

this includes:
- [ ] run_mapswipe_workers.__main__
---
- [x] basic.BaseFunctions.run_import()
---
- [x] basic.BaseProject.import_project()
- [x] basic.BaseProject.set_tasks_postgres()
- [x] basic.BaseProject.set_groups_postgres()
--- 
- [x] basic.BaseProject.delete_project()
- [x] basic.BaseProject.delete_local_files()
--- 
- [ ] ProjectTypes.BuildArea.BuildAreaProject.kml_to_file()
--- 
- [ ] ProjectTypes.Footprint.FootprintProject.__init__()
- [ ] ProjectTypes.Footprint.FootprintProject.check_input_geometries()

**Comment by Matthias-Schaub** [comment]
In the root of mapswipe_workers module there is now a definitions.py with path variables (eg. DATA_PATH, CONF_PATH).

Import those when needed instead of passing output_path as parameter:
`from mapswipe_workers.definitions import DATA_PATH`

**Comment by Hagellach37** [comment]
@Matthias-Schaub is this done and we can close the issue?
