### ISSUE TITLE
improve module structure

### ISSUE THREAD

**Issue by maze2point0** [mapswipe/python-mapswipe-workers#77]
import_firebase_to_psql.py
+
migrate_mysql_psql.py placed in /utils for now. But actually they don't fit in there thematically as the purpose for these scripts is just of interest for a transition between database infrasctructures.

I'd propose /aux as the better palce

**Comment by Matthias-Schaub** [comment]
Those scripts are not used by the module and should be used only once. Therefor a good place is in a directory called `scripts/` outside of the module.

**Comment by maze2point0** [comment]
implemented in
2938256638f01ace657f68b071885e0b4e2b31ed
