### ISSUE TITLE
Configuration handling

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#79]
Configuration path should either be at cfg/configuration.json or be given by the user.
Make sure configuration path handling is robust (works in docker, virtual env., etc.).

**Comment by maze2point0** [comment]
stumbled across some errors related to this. 
Think we need some documentation here

```FileNotFoundError: [Errno 2] No such file or directory: '/python-mapswipe-workers/mapswipe_workers/configuration.json'
```

https://github.com/mapswipe/python-mapswipe-workers/blob/d63664a02b1267f1867f67f90862e94e3f4ac217/mapswipe_workers/definitions.py#L4

I need to put the configurations.json in `/mapswipe_workers` before runing setup.py or docker compose in order to have a workin module?

**Comment by maze2point0** [comment]
`File "/python-mapswipe-workers/mapswipe_workers/ProjectTypes/BuildArea/BuildAreaImport.py", line 80, in validate_geometries
    os.mkdir('{}/input_geometries'.format(DATA_PATH))
FileNotFoundError: [Errno 2] No such file or directory: '/python-mapswipe-workers/mapswipe_workers/data/input_geometries'`

data folder too, now in the module path?

**Comment by Matthias-Schaub** [comment]
The config will be copied by `utils/path_helper.py` when using `run_mapswipe_workers.py` to start processes. `path_helper.py` will either look at default path wich `run_mapswipe_workers.py` will generate relativav to its location or it will look at given path. You can specify a custom location for your config either by passing `--config` argument when running `run_mapswipe_workers.py` or run `utils/path_helper.py` manually:
```python
from utils import path_helper
path_helper.copy_config(path)
```

Changed data path to the old path again. Not quite sure how to handle custom data path.

**Comment by Matthias-Schaub** [comment]
Until fixed the configuration path is hard coded in `mapswipe_workers/definitions.py`. This should work, if Mapswipe Workers is installed and running inside a Docker Container. For custom setup adjust the `ROOT_PATH` variable accordingly.

This is also be documented in the debugging section of the documentation: https://mapswipe-workers.readthedocs.io/en/benni.new-project-types/setup.html

**Comment by Matthias-Schaub** [comment]
For easy adoption by other developers we should adhere to standart practice regarding the configuration path. At the moment we create a new directory at the root of the entire filesystem called mapsipe_workers where everything (config, data/) is stored.
See this Stackoverflow to get an overview about places to store configuration:
https://stackoverflow.com/questions/7567642/where-to-put-a-configuration-file-in-python

If using Docker the configuration should probably be copied into the container because of security.

**Comment by Matthias-Schaub** [comment]
When using docker the configuration now will by copied from the config/ directory into the docker container.
If no docker is used for the setup (installing locally using setup.py) following directories will be created/used:

- Config: `/usr/share/config/mapswipe_workers/`
- Data: `/var/log/mapswipe_workers/`
- Logs: `/var/lib/mapswipe_workers/`
