### ISSUE TITLE
groups completed count in postgres is not updated!

### ISSUE THREAD

**Issue by maze2point0** [mapswipe/python-mapswipe-workers#81]
We need to set groups completed count in postgres when run_update is executed. Otherwise we have an inconsistency in the completedcount attribute for projects and corresponding groups.

**Comment by maze2point0** [comment]
done in
40a8e9cba5b32b9d4380f0d9885ab2d010964b39

**Comment by Hagellach37** [comment]
it seems that the completed count is not updated in the groups table. it is uploeaded to groups_progress but nothings changes in groups.

**Comment by Hagellach37** [comment]
dc4f29fa5ab3cb5a4b4ccadba946c012138b6d25

make sure to run the query. ;)
