### ISSUE TITLE
Tutorial create page -> Scenario : Prepare a set of icons for Scenarios

### ISSUE THREAD

**Issue by udaynwa** [mapswipe/python-mapswipe-workers#842]

**Comment by samshara** [comment]
@udaynwa  @frozenhelium  @shreeyash07 All the icons are from

- https://github.com/mapswipe/mapswipe/blob/feature/support-dynamic-options-and-info-pages/src/shared/common/SvgIcons.js

- https://github.com/mapswipe/mapswipe/tree/feature/support-dynamic-options-and-info-pages/src/shared/views/assets

**Comment by frozenhelium** [comment]
@samshara here's the added keys
```js
{
  generalTap: 'tap_icon.png',
  tap: 'tap_icon_angular.png',
  oneTap: '1_Tap_Black.png',
  twoTap: '2_Tap_Black.png',
  threeTap: '3_Tap_Black.png', 
}
```
