### ISSUE TITLE
MapRoulette integration documentation

### ISSUE THREAD

**Issue by udaynwa** [mapswipe/python-mapswipe-workers#850]

**Comment by udaynwa** [comment]
## Findings (as of June 14)

- 3 majors steps while makinga MapRoulette mission from MapSwipe building validation data;
  - Download MapSwipe feature validation project data
  - Modify the project data and upload in MapRoulette
  - Map in MapRoulette
- While creating a challenge(mission) in MapRoulette;
  - When creating a challenge using `Aggregated Results (with Geometry)` GeoJSON, `GeoJSON error: Polygons and MultiPolygons should follow the right hand rule` error occurred 
    - ![Image](https://github.com/mapswipe/python-mapswipe-workers/assets/72339626/c783acda-06e1-482a-b025-8af730dd48df)
  - When creating a challenge using `Moderate to High Agreement Yes Maybe Geometrics` GeoJSON, `GeoJSON error: old-style crs member is not recommended, this object is equivalent to the default and should be removed` error occurred
    - ![Image](https://github.com/mapswipe/python-mapswipe-workers/assets/72339626/128a89e1-96ec-446b-8c61-2b588a370f1e)

**Comment by udaynwa** [comment]
Looks like the geojson is failing because of geojson lint issue.

**Comment by udaynwa** [comment]
### While downloading data from MapSwipe and creating a challenge in MapRoulette
 
- Project : Finding buildings - Tonj County, South Sudan (1) German Red Cross (finished)
  - Link : https://mapswipe.org/en/project.html?projectId=-NWHpfmPVI8vi9HP6h1q
- Dataset name : Moderate to High Agreement Yes Maybe Geometries
- `GeoJSON error: old-style crs member is not recommended, this object is equivalent to the default and should be removed` error occured while uploading the GeoJSON file without editing
- No error occured when removing `"crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}}` from the GeoJSON file and uploading in the challenge
  - But no tasks were created in the Challenge after the upload was completed

cc @tnagorra

**Comment by frozenhelium** [comment]
- Do we also use project types other than "Footprint" for Map Roulette?
- We need to group the tasks by proximity so that there are fewer challenges.
- We need set-up a logic to filter out unwanted features from the export.

**Comment by danbjoseph** [comment]
- i think we are good with just footprint for now
- i was thinking about this. would we also need a max group size to keep challenges from getting too big? i don't know what a good max size would be.
- with the addition of project manager configurable answer options and sub options, setting up the right filter becomes difficult 🤔

**Comment by tnagorra** [comment]
@danbjoseph For the documentation, we can only mention about the min and the max size of the group.

@danbjoseph We should also brainstorm on ideas about how we can make the custom footprint answer options and the export for HOT compatible.

**Comment by danbjoseph** [comment]
where is the final documentation?

**Comment by udaynwa** [comment]
@danbjoseph , here is the write-up by @frozenhelium 
Link: https://github.com/mapswipe/python-mapswipe-workers/discussions/894
