### ISSUE TITLE
Create a warning banner for HOT Tasking Manager in custom input options of Footprint ONLY

### ISSUE THREAD

**Issue by udaynwa** [mapswipe/python-mapswipe-workers#879]

**Comment by danbjoseph** [comment]
what is the warning for?

**Comment by udaynwa** [comment]
@danbjoseph , the warning/alert is for HOT Tasking Manager Geometrics so that the managers use the values appropriately. Here is a screenshot of the warning. 
![Screenshot 2023-07-04 at 10 11 08](https://github.com/mapswipe/python-mapswipe-workers/assets/72339626/108f0c02-69e9-4ef9-beaf-a24b6e780171)
